### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by evanbrociner** [plandes/mimicsid#1]
Does anyone have any insights into installing the package without the dependency errors?

<img width="1627" alt="Screenshot 2023-02-10 at 11 00 09 AM" src="https://user-images.githubusercontent.com/33792805/218141521-fdf743c6-9c90-47e9-9736-a0fc26aa7cb1.png">

**Comment by plandes** [comment]
Is this from a pip install or are you building from the source?

**Comment by evanbrociner** [comment]
I used:

`pip3 install zensols.mimicsid `

on a new Google Colab notebook

**Comment by plandes** [comment]
I was in the middle of updating the model for this package and it looks like its dependencies got ahead of me. I have cut a new release, so retry with `pip3 install -U zensols.mimicsid`.

**Comment by evanbrociner** [comment]
Thanks so much for the quick replies. I am looking forward to using the package. I am still getting the same errors; it is having trouble finding specific versions of the dependent packages. Do you think the error happens because the package versions are not specified in the requirements file?

**Comment by plandes** [comment]
@evanbrociner The package has two requirements:

```python
zensols.deepnlp~=1.7.0
zensols.mimic~=1.0.0
```

If you follow these dependencies through, it should be getting `zensols.install==0.2.0`, not 0.1.0 and not 0.0.1.

I'm sorry I can't help you more, I don't have much experience with Google Collab.  I would recommend getting spaCy 3.2.4 installed first, as I've had issues with the kinds of errors your getting with the resolver.  Then installing the others.  Or even just going directly with the legacy pip resolver:

```bash
pip install -U zensols.mimicsid --use-deprecated=legacy-resolver
```

**Comment by plandes** [comment]
@evanbrociner I tried the last pip install specifying the resolver and it worked on a clean virtual environment.  If it still doesn't work in Google Collab, it might have something to do with Google's environment.  Feel free to open the issue back up if you continue to have problems.

**Comment by plandes** [comment]
I have verified this is an issue with the spaCy 3.2 package needing the `--use-deprecated=legacy-resolver` flag.  However, if you're still having issues, there is now a [Docker image](https://github.com/plandes/mimicsid#docker) available as well.  However, you will need to build or obtain a MIMIC-III database for any access to it.
