### ISSUE TITLE
Issue with "pip install zensols.mimicsid"

### ISSUE THREAD

**Issue by griff4692** [plandes/mimicsid#3]
I'm installing from a python venv from python 3.10

```
Collecting psycopg2~=2.9.9
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-m5siyzmf/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-m5siyzmf/psycopg2.egg-info/PKG-INFO 
      writing dependency_links to /tmp/pip-pip-egg-info-m5siyzmf/psycopg2.egg-info/dependency
_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-m5siyzmf/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-m5siyzmf/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
```

**Comment by plandes** [comment]
It can't install Postgres Python database drivers because it can't find the Postgres client install (`pg_config` is the client native configuration file).  It compiles against the Postgres client and uses this library to access the MIMIC-III dataset via Postgres.

First try (statically linked against the Postgres client):
```bash
pip install psycopg2-binary
```

If that doesn't work, and you only want to use the model, you can force install the `zensols.dbutilpg` package to make pip happy:

```bash
pip install --no-deps zensols.dbutilpg
```

If that still doesn't work, you may need to install the Postgres client.

**Comment by griff4692** [comment]
Thanks!

```pip install psycopg2-binary``` 

works and then I ran

`pip install --no-deps zensols.mimicsid`

But getting the below when I try to import it.   Thanks for the help!

```
>>> from zensols.mimicsid import PredictedNote, ApplicationFactory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/weka/home-griffin/envs/data/lib/python3.9/site-packages/zensols/mimicsid/__init__.py", line 17, in <module>
    from .domain import *
  File "/weka/home-griffin/envs/data/lib/python3.9/site-packages/zensols/mimicsid/domain.py", line 12, in <module>
    from zensols.persist import persisted, PersistableContainer
ModuleNotFoundError: No module named 'zensols.persist'
```

**Comment by plandes** [comment]
You need to remove the `--no-deps` from the `zensols.mimicsid` pip install (that was only for the the `zensols.dbutilpg` package).  The other dependencies are needed for the former.

This package has upgraded to spaCy 3.6 so the legacy resolver is no longer needed and everything should install.  The only exception would be the `nmslib` Python library, which is totally unrelated.  If you have problems with that package let me know.

**Comment by griff4692** [comment]
> You need to remove the `--no-deps` from the `zensols.mimicsid` pip install (that was only for the the `zensols.dbutilpg` package). The other dependencies are needed for the former.
> 
> This package has upgraded to spaCy 3.6 so the legacy resolver is no longer needed and everything should install. The only exception would be the `nmslib` Python library, which is totally unrelated. If you have problems with that package let me know.

Got it - I couldn't install `dbutilpg`

```
ERROR: Could not find a version that satisfies the requirement zensols.dbutilpg (from versions: none)
ERROR: No matching distribution found for zensols.dbutilpg
```

**Comment by plandes** [comment]
Sorry, ignore `zensols.dbutilpg`, the pip package name is `zensols.dbpg`.  But that should have installed just fine with `pip install zensols.mimisid`.  The missing `zensols.persist` mean it did not install the `mimicsid` dependency (different package).

Are you still getting that error?  If not, what's the error now?

**Comment by griff4692** [comment]
It's the same error but now slightly different location

```
Collecting psycopg2~=2.9.9 (from zensols.dbpg~=1.3.0->zensols.mimic<1.7.0,>=1.5.1->zensols.mimicsid)
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Installing build dependencies ... \

|
done

  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running egg_info
      writing psycopg2.egg-info/PKG-INFO
      writing dependency_links to psycopg2.egg-info/dependency_links.txt
      writing top-level names to psycopg2.egg-info/top_level.txt
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
```

**Comment by plandes** [comment]
The problem is the `mimic` requires `psycopg2 `. The easiest way to fix it is install it.  This looks like either macOS or Linux.  Either should be easy to install.  If this is macOS do this:

```bash
brew install libpq
brew install --with-clang llvm
CC="$(brew --prefix llvm@11)/bin/clang" \
	PATH="$$PATH:$(brew --prefix libpq)/bin" \
	pip install 'psycopg2~=2.9.9'
```

If Linux on Debian or some variable (which includes Ubuntu), this should work:
```bash
sudo apt-get install -y postgresql-client
```

Let me know how this goes.

**Comment by griff4692** [comment]
I'm getting the same error unfortunately -- is there a way to just use the section classification & segmentation model?

My use case is just to split MIMIC into sections so that I can filter out low quality sections for LLM pre-training. 

I've used Clarity NLP in the past for section tagging but was interested in trying MIMIC sid

**Comment by plandes** [comment]
Yes, others have had this issue and gotten by it, but it's still a pain.  It's like this because Postgres was "hardwired" from the beginning to train the model.  However, since then, I added SQLite as an option.  I'll look into making that the default and having Postgres optional.

Let me take a look and I'll get back to you soon.

**Comment by plandes** [comment]
Update the mimic package (note the `-U`):
```bash
pip install -U zensols.mimic
```

Let me know how it goes.

**Comment by plandes** [comment]
@griff4692 Did you get it working?  The last update was to make SQLite the default over Postgres, which doesn't require the Postgres client.

**Comment by griff4692** [comment]
Thanks - I was able to install but now getting an import error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

I don't have sudo access on our cluster so will have to figure out a way around this

**Comment by plandes** [comment]
No idea since I have not written any Tk code, and to my knowledge, there are no libraries I'm using that uses Tk.

Your stack trace doesn't give me where in any code I've written it's trying to access Tk.

Have you tried [installing it with pip](https://python-forum.io/thread-37886.html)?

If that doesn't work, you could compile Python and tcl/tk from source.

I can't help you with this one.

**Comment by plandes** [comment]
@griff4692 

I've made some upstream changes, namely an import that should prevent the need of Tcl/Tk.  Try `pip install -U zensols.mimicsid` again and let me know how it goes.
